### ISSUE TITLE
How to use as component in my application?

### ISSUE THREAD

**Issue by joe-berg-colossus** [donotebase/quasar-tiptap#34]
I'm a little confused how to use this as a component in my application. Specifically, I am confused how to properly pass data from my parent component into the `<quasar-editor />`.  

The code below will pass the data from `episode.keyLessons` in my parent component into the editor. However, when I try and type in the editor, the spacebar key does not register. If the cursor is in the `<h1>` section at the top and any key is pressed, the cursor immediately jumps down to the `<p>` section of the editor without me clicking there. 

What I have tried:
**Editor.vue**
```
<template>
  <div>
    <quasar-tiptap v-bind="options" @update="onUpdate" />
  </div>
</template>

<script>
import { QuasarTiptap, RecommendedExtensions } from "quasar-tiptap";
import "quasar-tiptap/lib/index.css";

export default {
  name: "Editor",
  props: ['value'],
  data() {
    return {
      options: {
        content: '',
        editable: true,
        extensions: [
          ...RecommendedExtensions
          // other extenstions
          // name string, or custom extension
        ],
        toolbar: [
          "add-more",
          "separator",
          "bold",
          // other toolbar buttons
          // name string
        ]
      },
      json: "",
      html: ""
    };
  },
  components: {
    QuasarTiptap
  },
  methods: {
    onUpdate({ getJSON, getHTML }) {
      this.json = getJSON();
      this.html = getHTML();
      this.$emit('update', this.html)
    }
  },
  watch: {
    value: {
      handler(newVal, oldVal) {
        this.options.content = newVal;
        console.log(`value changed: ${newVal}`);
      },
      immediate: true
    }
  },
  mounted() {
    // set language dynamically
    this.$o.lang.set("en-us");
  }
};
</script>
```

**Parent.vue**
```
<template> 
   <Editor v-model="episode.keyLessons" @update="update" />
</template>

<script>
data: () => ({
   episode: {
      keyLessons: null,
   }
}),
methods: {
   update(value) {
         this.episode.keyLessons = value;
       },
}
</script>
```

**Comment by jaybo** [comment]
I'm guessing this question is partly answered here:  https://stackoverflow.com/questions/64469357/how-to-pass-data-into-quasar-tiptap-editor-from-parent-component-in-vuejs, regarding the strange mouse activity.  I've followed the advice given there in my own app, but still have occasional `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders` warnings from Vue if the content has embedded images.

Like the original poster, given a situation where the app want to modify the view model (app->component->quasar-tiptap) I've been unable to pass in a v-model from app into the `content` property of the component.

I believe it's necessary to implement `setContent()` completely.  From reading the code, it looks like the existing version just reloads  `content` instead of letting you pass in a completely new HTML tree.
